server:
  port: 8080
spring:
  h2:
    datasource:
      generate-unique-name: false
      name: libraryH2
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:libraryH2
    username: sa
    password: